version: '3.7'
services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=pg_admin
      - POSTGRES_DB=chatCenter
      - POSTGRES_PASSWORD=examplepassq
      - PGDATA=/var/lib/postgresql/data/pgdata