version: '3.8'

services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    labels:
      - traefik.enable=false
    networks:
      - internal
  
  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      - traefik.enable=false
    networks:
      - internal

  flower:
    image: mher/flower:0.9.5
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
    ports:
      - 5555:5555
    command: ["flower", "--broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq", "--port=5555"]
    labels:
      - traefik.backend=flower
      - traefik.frontend.rule=Host:flower.chatcenter.hyfi.dev
      - traefik.docker.network=web
      - traefik.port=5555
    networks:
      - internal
      - web

  api:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    env_file:
      - ./api/.env
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/
      - /usr/src/node_modules
    ports: 
      - 3000:3000
    labels:
      - traefik.backend=api
      - traefik.frontend.rule=Host:api.chatcenter.hyfi.dev
      - traefik.docker.network=web
      - traefik.port=3000
    networks:
      - internal
      - web

  webhook:
    build: 
      context: ./webhook
      dockerfile: dockerfile.dev
    env_file:
      - ./webhook/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    ports:
      - 4000:4000
    labels:
      - traefik.backend=webhook
      - traefik.frontend.rule=Host:wh.chatcenter.hyfi.dev
      - traefik.docker.network=web
      - traefik.port=4000
    networks:
      - internal
      - web

  websocket:
    build:
      context: ./websocket
      dockerfile: dockerfile.dev
    env_file:
      - ./websocket/.env
    ports:
      - 5000:5000
    labels:
      - traefik.backend=websocket
      - traefik.frontend.rule=Host:ws.chatcenter.hyfi.dev
      - traefik.docker.network=web
      - traefik.port=5000
    networks:
      - internal
      - web

volumes:
  dbdata:

networks:
  web:
    external: true
  internal:
    external: false