version: '3.7'

networks:
  web:
    external: true
  internal:
    external: false

services:

  postgres:
    image: 'postgres'
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=chatCenter
      - POSTGRES_PASSWORD=examplepassq
      - PGDATA=/var/lib/postgresql/data/pgdata
  
  node:
    container_name: node
    hostname: node
    build: 
      context: ./Api
      dockerfile: dockerfile
    volumes: 
      - ./Api:/home/node/app
    ports:
      - '3005:3005'

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672" 

  webhook:
    build: ./webhook
    depends_on: 
      - rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  
  websocket:
    build: ./websocket
    hostname: websocket
    ports:
      - "5000:5000"
    environment: 
      FLASK_ENV: development
    
    networks:
      - internal
      - web
