FROM python:3.8

COPY ["./requirements.txt", "/usr/src"]

WORKDIR /usr/src

RUN pip install -r requirements.txt

COPY [".", "/usr/src/"]

EXPOSE 4000

ENTRYPOINT gunicorn -b 0.0.0.0:4000 wsgi:app | celery -A task worker -B -l info